export enum Abordagem {
  PSICANALITICA = 'PSICANALITICA',
  COMPORTAMENTAL = 'COMPORTAMENTAL',
  COGNITIVA = 'COGNITIVA',
  HUMANISTA = 'HUMANISTA',
  GESTALT = 'GESTALT',
  SISTEMICA = 'SISTEMICA',
  BIOPSICOSSOCIAL = 'BIOPSICOSSOCIAL',
  EVOLUCIONISTA = 'EVOLUCIONISTA',
  NEUROPSICOLOGIA = 'NEUROPSICOLOGIA',
  FENOMENOLOGIA = 'FENOMENOLOGIA',
  PSICOLOGIASOCIAL = 'PSICOLOGIASOCIAL',
}
