export enum Genero {
  CISGENERO = 'CISGENERO',
  TRANSGENERO = 'TRANSGENERO',
  NAO_BINARIO = 'NAO-BINARIO',
  AGENERO = 'AGENERO',
  BIGENERO = 'BIGENERO',
  POLIGENERO = 'POLIGENERO',
  GENERO_FLUIDO = 'GENERO-FLUIDO',
}
