services:
  db:
    image: postgres:16
    container_name: acolhe_jovem_postgres_container
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - acolhe_jovem_network

  app:
    container_name: acolhe_jovem_app_container
    environment:
      DB_HOST: 'db'
      DATABASE_URL: 'postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}?schema=public'
    volumes:
      - ./src:/app/src

    ports:
      - '3001:3000'
    networks:
      - acolhe_jovem_network
    depends_on:
      - db

    build:
      context: .
      dockerfile: Dockerfile

networks:
  acolhe_jovem_network:
    driver: bridge
