version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: acolhe_jovem_postgres_container
    environment:
      POSTGRES_DB: acolhe_jovem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - '5432:5432'
    networks:
      - acolhe_jovem_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: kalini/acolhe-jovem-deploy
    container_name: acolhe_jovem_app_container
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgresql://postgres:123456@acolhe_jovem_postgres_container:5432/acolhe_jovem?schema=public'
    ports:
      - '3000:3000'
    networks:
      - acolhe_jovem_network

networks:
  acolhe_jovem_network:
    driver: bridge

volumes:
  postgres_data:
