export enum Especialidade {
  CLINICA = 'CLINICA',
  HOSPITALAR = 'HOSPITALAR',
  EDUCACIONAL = 'EDUCACIONAL',
  ORGANIZACIONAL = 'ORGANIZACIONAL',
  PSICOPEDAGOGIA = 'PSICOPEDAGOGIA',
  PSICOMOTRICIDADE = 'PSICOMOTRICIDADE',
  SOCIAL = 'SOCIAL',
  NEUROPSICOLOGIA = 'NEUROPSICOLOGIA',
}
